num1 = float(input("First number: "))
num2 = float(input("Second number: "))
num3 = float(input("Third number: "))
Maximum = max(num1, num2, num3)
Minimum = min(num1, num2, num3)
print(f"The maximum number is: {Maximum}")
print(f"The minimum number is: {Minimum}")